// P5.2A-1 Foundation Split: shared runtime state.
let activeModule = localStorage.getItem(ACTIVE_MODULE_KEY) || "dashboard";
let authCallbackCaptured = false;
let view = localStorage.getItem("wl_view") || "center";
if (view === "warroom") view = "library";
if (view === "capture") view = "center";
let hasOsShellState = localStorage.getItem(OS_OPEN_TABS_KEY) !== null;
let openTabs = readJson(OS_OPEN_TABS_KEY, []);
let activeWorkspace = localStorage.getItem(OS_ACTIVE_WORKSPACE_KEY) || "dashboard";
let recentWorkspaces = readJson(OS_RECENT_WORKSPACES_KEY, []);
let selected = new Date();
let selectedMonth = monthKey(selected);
let entries = [];
let profile = readJson("wl_profile", null);
let workProfile = readJson("wl_work_profile", null);
let feedback = readJson("wl_feedback", {});
let session = readJson(AI_OS_SESSION_KEY, null);
let library = [];
let knowledgeUnits = [];
let knowledgeRecommendationCandidates = [];
let viewingKnowledgeId = null;
let editingLibraryId = null;
let editingWorkMemoryName = null;
let learningKnowledgeDraft = null;
let editingEntryId = null;
let captureSeed = null;
let sidebarOpen = false;
let mobileCalendarOpen = false;
let mobileWorklogTab = "time";
let aiTodaySuggestionIndex = Number(localStorage.getItem(AI_TODAY_SUGGESTION_INDEX_KEY) || 0);
let conversationMessagesState = null;
let conversationPendingState = undefined;
let conversationRefreshTimer = null;
const AI_REASON_QUEUE_SIZE = 5;
